version: "3"
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "1337:80"
      - "3001:81"
    depends_on:
      - server
      - client
  client:
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - type: volume
        source: client_volume
        target: /app/node_modules
      - type: bind
        source: ./client
        target: /app
  server:
    build:
      dockerfile: Dockerfile
      context: ./server
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    volumes:
      - type: volume
        source: server_volume
        target: home/node/app
      - type: bind
        source: ./server
        target: home/node/app
    command: npm run start

  postgres:
        image: postgres:11
        restart: always

        ports:
            - 3303:5432

        environment:
            POSTGRES_PASSWORD: ${DATABASE_PASS}
            POSTGRES_USER: ${DATABASE_USER}
            POSTGRES_DB: ${DATABASE_DB}

  redis:
        image: 'redis:4-alpine'
        command: redis-server --requirepass ${REDIS_PASS}
        ports:
            - '6379:6379'

volumes:
  server_volume:
  client_volume:
