export enum StoreActionKey {
  SET_NAVIGATION_GROUP = 'SET_NAVIGATION_GROUP',

  SET_ACCOUNT = 'SET_ACCOUNT',
  SET_ACCOUNT_LOADING = 'SET_ACCOUNT_LOADING',

  RESET = 'RESET',

  SET_COUNTRIES = 'SET_COUNTRIES',
  ADD_COUNTRY = 'ADD_COUNTRY',
  EDIT_COUNTRY = 'EDIT_COUNTRY',

  SET_INCIDENTS = 'SET_INCIDENTS',
  ADD_INCIDENT = 'ADD_INCIDENT',
  EDIT_INCIDENT = 'EDIT_INCIDENT',
}
