version: "3"

services:
  api:
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - 5000
    ports:
      - 5000:5000
    depends_on:
      - postgres
      - redis
    links:
      - postgres
      - redis
    volumes:
      - ./:/home/node/app
    command: npm run start

  postgres:
    image: postgres:11
    restart: always
    ports:
      - 3303:5432
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASS}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_DB: ${DATABASE_DB}

  redis:
    image: "redis:4-alpine"
    command: redis-server --requirepass ${REDIS_PASS}
    ports:
      - "6379:6379"
  minio:
    hostname: minio
    image: minio/minio:RELEASE.2021-09-18T18-09-59Z
    container_name: minio

    volumes:
      - "./face-zone/data/:/data"
      - "./face-zone/config:/root/.minio"

    ports:
      - 5003:9000
      - 5004:9001
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server --console-address ":9001"  /data
  imgproxy:
    image: "darthsim/imgproxy:latest"
    ports:
      - "5005:8080"
    depends_on:
      - minio
    links:
      - minio
    environment:
      IMGPROXY_KEY: ${IMGPROXY_KEY}
      IMGPROXY_SALT: ${IMGPROXY_SALT}
      IMGPROXY_MAX_SRC_FILE_SIZE: 10485760
