export const BLOG_REPOSITORY = Symbol("BLOG_REPOSITORY");
export const BLOG_CATEGORY_REPOSITORY = Symbol("BLOG_CATEGORY_REPOSITORY");

export const BLOG_SERVICE = Symbol("BLOG_SERVICE");
export const BLOG_CATEGORY_SERVICE = Symbol("BLOG_CATEGORY_SERVICE");